{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "\n",
    "sys.path.append(os.path.abspath(\"../src\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.linear_model import Ridge\n",
    "from sklearn.metrics import mean_squared_log_error\n",
    "from preprocessing import preprocess_pipeline\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/marcosalerno/store_sales/src/preprocessing.py:67: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n",
      "  df.fillna(method='bfill', inplace=True)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>sales</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>3000888</td>\n",
       "      <td>37.126723</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>3000889</td>\n",
       "      <td>36.473651</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3000890</td>\n",
       "      <td>41.065743</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3000891</td>\n",
       "      <td>135.703415</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>3000892</td>\n",
       "      <td>34.580789</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        id       sales\n",
       "0  3000888   37.126723\n",
       "1  3000889   36.473651\n",
       "2  3000890   41.065743\n",
       "3  3000891  135.703415\n",
       "4  3000892   34.580789"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Run Preprocessing Pipeline\n",
    "data_path = '../data/store-sales-time-series-forecasting/'\n",
    "df = preprocess_pipeline(data_path)\n",
    "df.head()\n",
    "\n",
    "# Select features and target\n",
    "features = ['store_nbr', 'family', 'onpromotion', 'dayofweek', 'month', 'year', 'day', 'is_weekend']\n",
    "X = df[features]\n",
    "y = df['sales']\n",
    "\n",
    "# Train Ridge Regression model\n",
    "model = Ridge(alpha=1.0)\n",
    "model.fit(X, y)\n",
    "\n",
    "# Load and prepare test data\n",
    "test = pd.read_csv(f'{data_path}/test.csv', parse_dates=['date'])\n",
    "test['dayofweek'] = test['date'].dt.dayofweek\n",
    "test['month'] = test['date'].dt.month\n",
    "test['year'] = test['date'].dt.year\n",
    "test['day'] = test['date'].dt.day\n",
    "test['is_weekend'] = test['dayofweek'].isin([5, 6]).astype(int)\n",
    "test['family'] = test['family'].astype('category').cat.codes\n",
    "test['store_nbr'] = test['store_nbr'].astype('category')\n",
    "X_test = test[features]\n",
    "\n",
    "# Make predictions and reverse log transform\n",
    "y_pred = model.predict(X_test)\n",
    "y_pred = np.expm1(y_pred)\n",
    "y_pred = np.clip(y_pred, 0, None)\n",
    "\n",
    "# Format submission\n",
    "submission = pd.DataFrame({\n",
    "    'id': test['id'],\n",
    "    'sales': y_pred\n",
    "})\n",
    "submission.to_csv('submission.csv', index=False)\n",
    "submission.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "        cached_call, estimator, *args, **routed_params.get(name).score\n",
      "    )\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "    return np.sqrt(mean_squared_log_error(y_true, y_pred))\n",
      "                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "        cached_call, estimator, *args, **routed_params.get(name).score\n",
      "    )\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "    return np.sqrt(mean_squared_log_error(y_true, y_pred))\n",
      "                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "        cached_call, estimator, *args, **routed_params.get(name).score\n",
      "    )\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "    return np.sqrt(mean_squared_log_error(y_true, y_pred))\n",
      "                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "        cached_call, estimator, *args, **routed_params.get(name).score\n",
      "    )\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "    return np.sqrt(mean_squared_log_error(y_true, y_pred))\n",
      "                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cross-validated RMSLE scores: [nan nan nan nan nan]\n",
      "Mean RMSLE: nan\n",
      "Fitting 5 folds for each of 12 candidates, totalling 60 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "        cached_call, estimator, *args, **routed_params.get(name).score\n",
      "    )\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "    return np.sqrt(mean_squared_log_error(y_true, y_pred))\n",
      "                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py\", line 949, in _score\n",
      "    scores = scorer(estimator, X_test, y_test, **score_params)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 288, in __call__\n",
      "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/var/folders/jc/16b4bhxs5pb1zk_fkwc7lk280000gn/T/ipykernel_77404/2192205012.py\", line 23, in rmsle\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/utils/_param_validation.py\", line 216, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py\", line 746, in mean_squared_log_error\n",
      "    raise ValueError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "ValueError: Mean Squared Logarithmic Error cannot be used when targets contain values less than or equal to -1.\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/marcosalerno/store_sales/venv/lib/python3.13/site-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best RMSLE score: nan\n",
      "Best parameters: {'learning_rate': 0.05, 'max_depth': 4, 'n_estimators': 100}\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>sales</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>3000888</td>\n",
       "      <td>4.437427</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>3000889</td>\n",
       "      <td>0.748046</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3000890</td>\n",
       "      <td>9.929897</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3000891</td>\n",
       "      <td>2195.675293</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>3000892</td>\n",
       "      <td>1.738880</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        id        sales\n",
       "0  3000888     4.437427\n",
       "1  3000889     0.748046\n",
       "2  3000890     9.929897\n",
       "3  3000891  2195.675293\n",
       "4  3000892     1.738880"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from xgboost import XGBRegressor\n",
    "\n",
    "# Convert categorical features to numeric codes for XGBoost\n",
    "X_xgb = X.copy()\n",
    "X_test_xgb = X_test.copy()\n",
    "\n",
    "for col in X_xgb.select_dtypes(include='category').columns:\n",
    "    X_xgb[col] = X_xgb[col].cat.codes\n",
    "\n",
    "for col in X_test_xgb.select_dtypes(include='category').columns:\n",
    "    X_test_xgb[col] = X_test_xgb[col].cat.codes\n",
    "\n",
    "'''# Train XGBoost model\n",
    "xgb_model = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)\n",
    "xgb_model.fit(X_xgb, y)'''\n",
    "\n",
    "\n",
    "from sklearn.model_selection import TimeSeriesSplit, cross_val_score\n",
    "from sklearn.metrics import mean_squared_log_error, make_scorer\n",
    "\n",
    "# Define RMSLE scorer\n",
    "def rmsle(y_true, y_pred):\n",
    "    y_pred = np.clip(y_pred, 0, None)\n",
    "    return np.sqrt(mean_squared_log_error(y_true, y_pred))\n",
    "\n",
    "rmsle_scorer = make_scorer(rmsle, greater_is_better=False)\n",
    "\n",
    "# TimeSeriesSplit CV\n",
    "tscv = TimeSeriesSplit(n_splits=5)\n",
    "\n",
    "xgb_model = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)\n",
    "\n",
    "cv_scores = cross_val_score(xgb_model, X_xgb, y, cv=tscv, scoring=rmsle_scorer)\n",
    "\n",
    "print(\"Cross-validated RMSLE scores:\", -cv_scores)\n",
    "print(\"Mean RMSLE:\", -np.mean(cv_scores))\n",
    "\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "\n",
    "param_grid = {\n",
    "    'n_estimators': [100, 300],\n",
    "    'learning_rate': [0.05, 0.1],\n",
    "    'max_depth': [4, 6, 8]\n",
    "}\n",
    "\n",
    "grid = GridSearchCV(\n",
    "    estimator=XGBRegressor(random_state=42),\n",
    "    param_grid=param_grid,\n",
    "    cv=tscv,\n",
    "    scoring=rmsle_scorer,\n",
    "    verbose=1,\n",
    "    n_jobs=-1\n",
    ")\n",
    "\n",
    "grid.fit(X_xgb, y)\n",
    "\n",
    "print(\"Best RMSLE score:\", -grid.best_score_)\n",
    "print(\"Best parameters:\", grid.best_params_)\n",
    "\n",
    "# Final model\n",
    "xgb_model = grid.best_estimator_\n",
    "\n",
    "\n",
    "# Predict with XGBoost\n",
    "xgb_preds = xgb_model.predict(X_test_xgb)\n",
    "# xgb_preds = np.expm1(xgb_preds)\n",
    "xgb_preds = np.clip(xgb_preds, 0, None)\n",
    "\n",
    "# Save XGBoost submission\n",
    "submission_xgb = pd.DataFrame({\n",
    "    'id': test['id'],\n",
    "    'sales': xgb_preds\n",
    "})\n",
    "submission_xgb.to_csv('submission_xgb.csv', index=False)\n",
    "submission_xgb.head()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
